{% set version = "1.9.4" %}

package:
    name: django-autoslug
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-autoslug/django-autoslug-{{ version }}.tar.gz
  sha256: aece8613eb173854462c656e91d81aa7ddfacaa49fb500d549f2143d1ce48721

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.7.10,<2

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import autoslug"

about:
  home: http://bitbucket.org/neithere/django-autoslug/
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: An automated slug field for Django

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
