{% set version = "1.9.3" %}

package:
    name: django-autoslug
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-autoslug/django-autoslug-1.9.3.tar.gz
  sha256: 790efc84246ad8b7106d94e79bff8eb14b94616e8765235784483832899bb40a

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.7.10,<2

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import autoslug"

about:
  home: http://bitbucket.org/neithere/django-autoslug/
  license: LGPL-3.0
  summary: An automated slug field for Django

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
