travis:
  secure:
    BINSTAR_TOKEN: goYwSPzObTxd4hl0yq6TOiYP4Y8wI3d0EoYeeJLrhpP9tlEywYGNoqJ1C0DIDKDisj/wUqQpu8g662F9N8slzy13Hefzr5/IeXj9QxCVvpjy7G48GjG4pM61rO8euK8likIu/XwEdaN4kjM3Y9ug5GDpeOGg5YC4oPog9GL4H5tdEJfyiD0Jp0NteLTXK154cMnetjsO/5NHKhv1WftHgtBUgz6h013MmdqKGyZbJCl2XejPg1k1nD3Y8a8536E0EZVa+TLj/ZRe1lIxk5i27Bl26uS+fiCSD473NyVOrU6ZxAaz6EIvVlCD2JIh4D7uv1u+TvYzz8Q4yXEEomBgRc9tu4LvfrV2w+wKWXXkxn+cvh14MQysWdIgcFYwW7tLWvlOFTWpxQ2Is3DeV9pP/yn4IkGFaWPhsNR/FyLVlKxZSvk17t6UjLdbKcHFjrGgGLrC+YylhAhR+H4kWyI1med7sg/nMN76okoeMNfPaE6y2rWasQikoEdqpZZhqMf4KngN8x7u4VrQN6htrjzRc5KeS0/NY7/V9axiarmUcPE7XuHK5oE5erKAKV35QmOVJIMgZpDhnoBbtxKhBUYPDV/BtRd3xkt3ykRoOH3EN5+ETrPtUfs8+koML678C516B+4xE8r+DUw/JFRQ0nRGHG2Hajy/2mvlyCcWqOZlWzE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
