travis:
  secure:
    BINSTAR_TOKEN: fmxh6fOSmEcwhuyA0Oc6bAqSH1sVofT/C8J0HxuTWyelTAI8b/fh9/b4d/Oclq6VwmuPPuF7efs/99aE5HZpUElFjX9pnUTpFoyLwIjCP/DS1+WOovjQIwEymS3azFGB2AZxybz6Bn7XplmHszMZvcIwcdxIRVo5hFtnL9plAluupAjPW3ETRzO+Dt6Ut/wZ9oDzxrytKOJ2O1ZfPOiAQvMDI5oQAAazd1LlvW2lcniD09ohmGZgWAdPVPdrwnCVcCeHBW0Q3DF2ifSk1QF/dnf0WAvZIAWAKD6BJAKInLPjRiYxzGCyylkbmM0U5LPU+AhqefT++PK0cP5sFfXudMunuVsaq+y98Gi2s87dfiGkVsccycbeFIKkcOV1yAOAM2YiIZx+P1UkDTJTYwoObQTBXVFKXlSgaeM2bV1bVCVAOMdndIlOTxV9SV04JGEjy3cqMdw4v19hjCA3EiTIKRkEyxAOfpNZ8ZyqZ39lcJTcM8/aRRfVfojLsfRnK8xmqR8mnX9XziAeE2fTccTMPrvpgAO+lG5c6cNNXowJTCZVhNbT4Kzib1vYIbzpW6+g3ZCiyfZ3Odq4yKo13IFH4yrIK+aiQwy98701sXfIbN4Q4ddqtnJh/IinY8vDLu69bbpbTMEaKQShI1AUwlOlRQPx305em7pA2X2/b64uR+c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
