travis:
  secure:
    BINSTAR_TOKEN: ff1d0zfiS+ZVebBcAPTJ5WFqy0K2atkZwnoDDXcacxRq5OKKpF0WUJOhFcQNK83oyaFd7/mEtj2naTrrmARDXizgMINMbo0m+I05DpH9wCEnfs0UuC0O2ZOgkNxhXz5FwNNZ1lJXHFJbFO3CegMDsY6EBFVl5R+89CPS4oXUSjXRcUQD3jb4KCedAutKwdT0s2C1Eu9snZlSHkIHBJNEJ65Q2UAIE5fuiYCzQhy7ZFyTE1IC6wvlEjDbvV0/Y3LhN5T6lcvWgFxsB7th6BRSckLEwaXTRWmhaehx6otdgpepJNUlp2BrNe+gL1CmeC1RnzmZxkiiuICaANf64GgOtLPnouwSALCjd3eUoDOPsZWA5QPYt4jJqbY1cFEQNbVTf3LcD5FQCmB/BEOga3I3iCi6+qxvLi5dKOjsFurwMpjvJgd0zHZXYoyJERFqnSxpUwdcb3hrlfU5F6sEN+Wrw6YytIRu/QbCfC9rHvT1EKnbxHKeVNGRmexxo+a5n7b56SqljsmnUXWw9Cj9VWy9Ek1nJ1QD+RmuHxsdVtF+Xa79Q9lEp+oYkVxE7MQl5rtQ5jt6HbQHiC4+0goMNXBkqbNu9TejvNBJOpjZIs5BtNw87jkA9EHeYyT8UFZyNVUdFbUo3HiCiwn0nt3U6lCfZnbg3ljjZBUCG9jnnRw4vjw=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
